[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/out"

[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "wss://pushup-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
