[build]
  base = "frontend"
  command = "npm install && SKIP_ENV_VALIDATION=true npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "wss://pushup-production.up.railway.app"
  SKIP_ENV_VALIDATION = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
